accounts/urls.py
from django.urls import path
from accounts.views import (
    user_login,
    user_logout,
    signup,
    profile,
    create_profile,
    edit_profile,
    follower_list,
)

urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("signup/", signup, name="signup"),
    path("profile/<int:id>/", profile, name="user_profile"),
    path("create/", create_profile, name="create_profile"),
    path("edit/<int:id>/", edit_profile, name="edit_profile"),
    path("followers/<int:id>/", follower_list, name="show_follow"),
]

arts/urls.py
from django.urls import path
from arts.views import (
    art_list,
    show_art,
    explore_art,
    upload_art,
    edit_art,
    create_tag,
    submitted,
    tag_list,
    edit_tag,
    submitted_edit,
    delete_art,
    delete_tag,
)


urlpatterns = [
    path("", art_list, name="art_list"),
    path("<int:id>/", show_art, name="show_art"),
    path("explore/", explore_art, name="explore"),
    path("upload/", upload_art, name="upload"),
    path("edit/<int:id>/", edit_art, name="edit"),
    path("create/", create_tag, name="create_tag"),
    path("submitted/", submitted, name="submitted"),
    path("submitted/edit/", submitted_edit, name="submitted_edit"),
    path("tag-list/", tag_list, name="tag_list"),
    path("edit-tag/<int:id>/", edit_tag, name="edit_tag"),
    path("delete/<int:id>/", delete_art, name="delete_art"),
    path("delete/tag/<int:id>/", delete_tag, name="delete_tag"),
]

peachbunni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import ResetPasswordView
from django.contrib.auth import views as auth_views


def redirect_home(request):
    return redirect("art_list")


urlpatterns = [
    path("", redirect_home, name="home"),
    path("admin/", admin.site.urls),
    path("arts/", include("arts.urls")),
    path("accounts/", include("accounts.urls")),
    path("password-reset/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/reset_complete.html"
        ),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField("Avatar", upload_to="profile-images")
    bio = models.TextField("Bio", max_length=150)

    def __str__(self):
        return self.user.username


class Follower(models.Model):
    name_of_follower = models.ForeignKey(
        User,
        related_name="name_of_followers",
        on_delete=models.CASCADE,
        null=True,
    )

    artist_followed = models.ForeignKey(
        User,
        related_name="artist_followeds",
        on_delete=models.CASCADE,
        null=True,
    )

    class Meta:
        unique_together = ("name_of_follower", "artist_followed")

    def __str__(self):
        return self.name_of_follower.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.forms import ModelForm
from accounts.models import Profile, Follower


username_validator = RegexValidator(
    r"^[a-zA-Z0-9][a-zA-Z0-9._]*[a-zA-Z0-9]$",
    "Invalid username - Alphanumerical characters and (_) and (.) allowed;"
    + " first and last must be alphanumerical.",
)


name_validator = RegexValidator(
    r"^[a-zA-Z]+( [a-zA-Z]+)*$", "Invalid Name - letters only."
)


password_validator = RegexValidator(
    r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%%^&*()_+={};:,.<>?~-]).*$",
    "Invalid password - Needs at least one uppercase,"
    + " one number, one lowercase, and one special symbol:"
    + r"[!@#$%%^&*()_+={};:,.<>?~-]",
)


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
                "name": "password",
            }
        ),
    )
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ["username", "password", "remember_me"]


class SignUpForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        max_length=30,
        required=True,
        validators=[
            username_validator,
        ],
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control",
            }
        ),
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if username:
            username = username.lower()
            return username

    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control",
            }
        ),
    )
    first_name = forms.CharField(
        max_length=30,
        required=True,
        validators=[
            name_validator,
        ],
        widget=forms.TextInput(
            attrs={
                "placeholder": "First Name",
                "class": "form-control",
            }
        ),
    )
    last_name = forms.CharField(
        max_length=30,
        validators=[
            name_validator,
        ],
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Last Name",
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        min_length=8,
        max_length=300,
        validators=[
            password_validator,
        ],
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
            }
        ),
    )
    password_confirmation = forms.CharField(
        min_length=8,
        max_length=300,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
            }
        ),
    )


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [
            "avatar",
            "bio",
        ]


class FollowerForm(ModelForm):
    class Meta:
        model = Follower
        fields = []

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from accounts.forms import LoginForm, SignUpForm
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from arts.models import Art
from accounts.models import Profile, Follower
from accounts.forms import ProfileForm, FollowerForm


# Create your views here.
def user_login(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        remember_me = form.cleaned_data["remember_me"]
        user = authenticate(
            request,
            username=username,
            password=password,
        )
        if not remember_me:
            request.session.set_expiry(0)
            request.session.modified = True
        if user is not None:
            login(request, user)
            return redirect("home")
    else:
        form = LoginForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def user_logout(request):
    logout(request)
    return redirect("login")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                if not last_name:
                    last_name = ""
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    first_name=first_name,
                    last_name=last_name,
                    password=password,
                )

                login(request, user)

                return redirect("home")
            else:
                form.add_error("password", "The passwords do not match!")
    else:
        form = SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "accounts/reset.html"
    email_template_name = "accounts/reset_email.html"
    subject_template_name = "accounts/reset_subject.txt"
    success_message = (
        "Please check your email for the instructions to reset your password. "
        "If you do not receiive an email,"
        "please re-enter the correct email address "
        "or check your spam folder. Thank you."
    )
    success_url = reverse_lazy("login")


@login_required(login_url="login")
def profile(request, id):
    artist = User.objects.get(id=id)
    arts = Art.objects.filter(artist=artist).order_by("-date")
    follower = Follower.objects.filter(artist_followed=artist)
    following = Follower.objects.filter(name_of_follower=artist)
    followed = Follower.objects.filter(
        name_of_follower=request.user, artist_followed=artist
    ).exists()

    context = {
        "art_list": arts,
        "artist": artist,
        "followers": follower,
        "following": following,
        "followed": followed,
    }

    if request.method == "POST" and "unfollow" in request.POST:
        follow = Follower.objects.filter(
            name_of_follower=request.user, artist_followed=artist
        )
        follow.delete()
        return redirect("user_profile", id=artist.id)

    if request.method == "POST" and "unfollow" not in request.POST:
        form = FollowerForm(request.POST)
        context = {
            "art_list": arts,
            "artist": artist,
            "followers": follower,
            "following": following,
            "followed": followed,
            "form": form,
        }
        if form.is_valid():
            follow = form.save(commit=False)
            follow.artist_followed = artist
            follow.name_of_follower = request.user
            follow.save()
            return redirect("user_profile", id=artist.id)
        else:
            form = FollowerForm()

    return render(request, "accounts/profile.html", context)


@login_required(login_url="login")
def create_profile(request):
    if Profile.objects.filter(user=request.user).exists():
        return redirect("edit_profile", id=request.user.profile.id)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect("user_profile", id=request.user.id)
    else:
        form = ProfileForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/create_profile.html", context)


@login_required(login_url="login")
def edit_profile(request, id):
    profile = Profile.objects.get(id=id)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save()
            return redirect("user_profile", id=id)
    else:
        form = ProfileForm(instance=profile)
    context = {
        "form": form,
    }
    return render(request, "accounts/edit_profile.html", context)


@login_required(login_url="login")
def follower_list(request, id):
    artist = User.objects.get(id=id)
    follower = Follower.objects.filter(artist_followed=artist)
    following = Follower.objects.filter(name_of_follower=artist)

    if request.method == "POST" and request.user == artist:
        follower_id = request.POST.get("follower_id")
        if follower_id:
            follow = Follower.objects.get(id=follower_id)
            follow.delete()
        followee_id = request.POST.get("followee_id")
        if followee_id:
            follow = Follower.objects.get(id=followee_id)
            follow.delete()
        return redirect("show_follow", id=artist.id)

    context = {
        "artist": artist,
        "follower": follower,
        "followee": following,
    }
    return render(request, "accounts/follow.html", context)

accounts/templates/accounts/create_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Create Profile
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header>
        <nav>
            <div>
                <p>
                    <a href="{% url 'art_list' %}">
                        <img class="sidebar"
                             src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'art_list' %}">
                        <img src="{% static 'navigation/home.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'user_profile' request.user.id %}">
                        <img src="{% static 'navigation/profile.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'explore' %}">
                        <img src="{% static 'navigation/explore.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'upload' %}">
                        <img src="{% static 'navigation/upload.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'logout' %}">
                        <img src="{% static 'navigation/logout.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="javascript: history.go(-1)">
                        <img src="{% static 'navigation/back.png' %}">
                    </a>
                </p>
            </div>
        </nav>
    </header>
    <main class="center">
        <div>
            <h1>Create Profile</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();">Upload</button>
            </form>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Edit Profile
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header>
        <nav>
            <div>
                <p>
                    <a href="{% url 'art_list' %}">
                        <img class="sidebar"
                             src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'art_list' %}">
                        <img src="{% static 'navigation/home.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'user_profile' request.user.id %}">
                        <img src="{% static 'navigation/profile.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'explore' %}">
                        <img src="{% static 'navigation/explore.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'upload' %}">
                        <img src="{% static 'navigation/upload.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'logout' %}">
                        <img src="{% static 'navigation/logout.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="javascript: history.go(-1)">
                        <img src="{% static 'navigation/back.png' %}">
                    </a>
                </p>
            </div>
        </nav>
    </header>
    <main class="center">
        <div>
            <h1>Edit Profile</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();">Upload</button>
            </form>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/follow.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Followers - {{ artist.username }}
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header>
        <nav>
            <div>
                <p>
                    <a href="{% url 'art_list' %}">
                        <img class="sidebar"
                             src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'art_list' %}">
                        <img src="{% static 'navigation/home.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'user_profile' request.user.id %}">
                        <img src="{% static 'navigation/profile.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'explore' %}">
                        <img src="{% static 'navigation/explore.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'upload' %}">
                        <img src="{% static 'navigation/upload.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'logout' %}">
                        <img src="{% static 'navigation/logout.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="javascript: history.go(-1)">
                        <img src="{% static 'navigation/back.png' %}">
                    </a>
                </p>
            </div>
        </nav>
    </header>
    <section class="profile">
        <div class="container-1">
            {% if artist.profile.avatar %}
                <div>
                    <img src="{{ artist.profile.avatar.url }}" height=200, width=200 />
                </div>
            {% else %}
                <div>
                    <img src="{% static 'images/sidebar_icon.png' %}" height=200, width=200 />
                </div>
            {% endif %}
        </div>
        <div class="container-2">
            <h1>
                <a href="{% url 'user_profile' artist.id %}">{{ artist.username }}</a>
            </h1>
            <div class="bio">{{ artist.profile.bio }}</div>
            <div class="bio">
                <br>
                <br>
                <a href="{% url 'show_follow' artist.id %}">Followers:</a> {{ follower.count }}
                <span></span>
                <a href="{% url 'show_follow' artist.id %}">Following:</a> {{ followee.count }}
            </div>
        </div>
    </section>
    <main class="follow">
        <div class="followers">
            <h2>Followers: {{ follower.count }}</h2>
            <ul>
                {% for follow in follower %}
                    <li>
                        {{ follow.name_of_follower }}
                        {% if request.user == artist %}
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="follower_id" value="{{ follow.id }}">
                                <button type="submit">Remove</button>
                            </form>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="following">
            <h2>Following: {{ followee.count }}</h2>
            <ul>
                {% for follow in followee %}
                    <li>
                        {{ follow.artist_followed }}
                        {% if request.user == artist %}
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="followee_id" value="{{ follow.id }}">
                                <button type="submit">Unfollow</button>
                            </form>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Login
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header class="center">
        <nav>
            <div>
                <p>
                    <img class="sidebar"
                         src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                </p>
            </div>
        </nav>
    </header>
    <main class="center">
        <div>
            <h1>Login</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();">Login</button>
            </form>
        </div>
        <div>
            <a href="{% url 'signup' %}">
                <button>Sign Up</button>
            </a>
            <br>
            <br>
            <a href="{% url 'password_reset' %}">
                <button>Forgot Password?</button>
            </a>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Profile - {{ artist.username }}
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header>
        <nav>
            <div>
                <p>
                    <a href="{% url 'art_list' %}">
                        <img class="sidebar"
                             src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'art_list' %}">
                        <img src="{% static 'navigation/home.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'user_profile' request.user.id %}">
                        <img src="{% static 'navigation/profile.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'explore' %}">
                        <img src="{% static 'navigation/explore.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'upload' %}">
                        <img src="{% static 'navigation/upload.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="{% url 'logout' %}">
                        <img src="{% static 'navigation/logout.png' %}">
                    </a>
                </p>
                <p>
                    <a class="navig" href="javascript: history.go(-1)">
                        <img src="{% static 'navigation/back.png' %}">
                    </a>
                </p>
            </div>
        </nav>
    </header>
    <section class="profile">
        <div class="container-1">
            {% if artist.profile.avatar %}
                <div>
                    <img src="{{ artist.profile.avatar.url }}" height=200, width=200 />
                </div>
            {% else %}
                <div>
                    <img src="{% static 'images/sidebar_icon.png' %}" height=200, width=200 />
                </div>
            {% endif %}
        </div>
        <div class="container-2">
            <h1>
                {{ artist.username }}
                <div class="links">
                    {% if artist == request.user %}
                        {% if artist.profile %}
                            <a href="{% url 'edit_profile' artist.profile.id %}">Edit</a>
                        {% else %}
                            <a href="{% url 'create_profile' %}">Create</a>
                        {% endif %}
                    {% else %}
                        {% if not followed %}
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();">Follow</button>
                            </form>
                        {% else %}
                            <form method="post">
                                {% csrf_token %}
                                <button name="unfollow">Unfollow</button>
                            </form>
                        {% endif %}
                    {% endif %}
                </div>
            </h1>
            <div class="bio">{{ artist.profile.bio }}</div>
            <div class="bio">
                <br>
                <br>
                <a href="{% url 'show_follow' artist.id %}">Followers:</a> {{ followers.count }}
                <span></span>
                <a href="{% url 'show_follow' artist.id %}">Following:</a> {{ following.count }}
            </div>
        </div>
    </section>
    <main class="profile-main">
        {% for item in art_list %}
            {% if item.private == False or item.artist == request.user %}
                <a href="{% url 'show_art' item.id %}">
                    <img class="item" src="{{ item.file.url }}">
                </a>
            {% endif %}
        {% endfor %}
    </main>
{% endblock content %}

accounts/templates/accounts/reset.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Reset Password
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header class="center">
        <nav>
            <div>
                <p>
                    <img class="sidebar"
                         src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                </p>
            </div>
        </nav>
    </header>
    <main class="center">
        <div>
            <h1>Reset Password</h1>
            <form method="post">
                {% csrf_token %}
                <label for="id_email">Email</label>
                <input type="email"
                       name="email"
                       class="form-control"
                       autocomplete="email"
                       maxlength="250"
                       required
                       id="id_email"
                       placeholder="Enter email" />
                <br>
                <button type="submit"
                        onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();">Submit</button>
            </form>
        </div>
        <div>
            <a href="{% url 'signup' %}">
                <button>Sign Up</button>
            </a>
            <br>
            <br>
            <a href="{% url 'login' %}">
                <button>Login</button>
            </a>
        </div>
    </main>
{% endblock content %}

accounts/templates/accounts/reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Reset Complete
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header class="center">
        <nav>
            <div>
                <p>
                    <img class="sidebar"
                         src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                </p>
            </div>
        </nav>
    </header>
    <main class="center">
        <div>
            <h1>Your password has been reset. You may go login.</h1>
            <div>
                <a href="{% url 'login' %}">
                    <button>Login</button>
                </a>
            </div>
        </main>
    {% endblock content %}

accounts/templates/accounts/reset_email.html
{% autoescape off %}
    To begin the password reset process for your account with {{ user.email }},
    click the link below:
    {{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}
    You may also copy-paste the URL into your brower.
    Thank you,
    Dev
{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Signup
{% endblock title %}
{% block content %}
    <link rel="stylesheet" href='{% static "css/accounts.css" %}'>
    <header class="center">
        <nav>
            <div>
                <p>
                    <img class="sidebar"
                         src="https://ih0.redbubble.net/avatar.8998414.140x140.jpg">
                </a>
            </p>
        </div>
    </nav>
</header>
<main class="center">
    <div>
        <h1>Signup</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button onclick="this.disabled=true;this.value='Submitting...'; this.form.submit();">Sign Up</button>
        </form>
    </div>
    <br>
    <div>
        <a href="{% url 'login' %}">
            <button>Login</button>
        </a>
    </div>
</main>
{% endblock content %}